# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 242c92f8a9367353849dfe01d97ede75312ffde59df12f69ca0ab82e33fbeba2ada893fa57594461e1d15adfea9f8eb009eac560e10ac2550456b028b43a978e

test:
  secret_key_base: 8be4618b3f85abf979ab2772b44d7246f4346b7c06894b80ac3a1957b62a3e091a64d9cfb53cf9c000bf76443564705a64e53eda56139e87e7bfc72f19c82ae4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
